create database sensor_db;

create table sensor
(
    id         int GENERATED by default as identity PRIMARY KEY ,
    name       varchar(100) not null unique,
    created_at timestamp
);

create table measurement
(
    id        int generated by default as identity primary key,
    value     decimal not null,
    raining   boolean not null,
    sensor_id int     references sensor (id) on delete set null
);

alter table measurement add column created_at timestamp;
